#
env:
  - TRAVIS_PULL_REQUEST=true

language: 
  - python

python:
  - 3.6
  - 3.5
  - 3.4

before_install:  # Earliest build step
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo "Not a PR, skipping" && exit; fi

install: 
  - pip install -U tox-travis 
  - pip install -r requirements.txt

script: 
  - tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: alejogiley
  password:
    secure: PQZxpnr3XNnVCVk0yzMqwY211lTTkEqVksU7XSJnHq18ISplLm4kBip9BLP0o6ErehZDW4wK2/boVN3QMUKKNsxgXBjyNqSvsKYGCMBb5oUOBQVO5ELph3/sUVIOtxZRUWnD1foOVRl4CWutXyUgXJhCvedwmF5s4p0apLBvk4XtSDKAZnML6yE1cK76b4FjPcjCBXAQT8B7Z1PsjvYKdX2YUGDq3uttdoZLB6RdH1wn7Dd0HA/SX+1Ucz3vHIjfDp9+r4lmjFEVEeSRt6x8H0zjVvzOQo78W3HfTV4IGeojFMXBAnG4YoCOyumO35rAC0RKxECyW9tPiSK6A51FZtzRNqPmT6PkEQ1w1wXWHP/RJzann5aWwXL22zmj/rfk+5iE7i42mrlQXlmO47UJqZHB5QSH9SvE8eTzKpSmszsbF/k9ygV1+YDmNK2hGsURdMH4Shb/O4CKdNcGFvFcfneYFQDnXcrzgBCcno7A3yS4rPQxi9lHkh3ASXyT0biADZ92t/3W0xWCldL2wuGuC27wy5jMxq3UvPg6QAZa/WBkRoJnMwHDg/YAKEeTksi/uViGdjRg7uz6JJZXSKAwMpZvUZTuy7TOft0UrxnjTdioTRON75/oMp2m0vs+D7vaxbZ/kkLopYUOPFuh3AM7odSiQrwf8bJe8A7QUE3r66w=
  on:
    tags: true
    repo: alejogiley/pypoc
    python: 3.6
#
