language: python
python:
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis && pip install -r requirements.txt
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: alejogiley
  password:
    secure: Bz4QcyI8nRbx8mcvPN71QUJ4PVGPmIEE+tDezamqqSaVTRxcjrcAyhVllgPbDpF/fEaB7m66wqyA5w5m+QtI1aQ7Vjcr05c/9afYLCbc4zMalg/ywtIky/uWkfEYN0UjtjfM6dHVfiSAQdQlJiXhpaGKJFsPtvnIjm0Ecb/8M1b6mdrOO92ZAOsqrkJMCQ49plcy8zzvjWwxw/SKKuLXNBn/UFezTVhLVgQ+XBWIgaBfLi00KHOgOZ/9XGoTE9GDx1kRO1sLSo4J+cV+u3yVyLElgV6ZsGI9BvLvZK+Vxqwy7aQDAAfT5NbNLiYNsBIqHrsFIyPhhWPMRC5PntiDJIZ/YVZs4hrikSIO3N9p01KDkPxwZa7g8bAlU9zWGRy935DbOMgVX3+M+uJ04J9B7LGnIARUEkUAlPkE4lohXFFQDnt3Oq3OdoIyIEuhIxHLMtrdXiYK39kHaDqXX5wKpTav/XRIZjMfL45b1xW4RlmsyWcVjmwYi2NfuRdDfJwfedNH+PQQraHW+jNtL+MJjEs9U7xCi13K+XiiOaPAyp1xJcw/22oE3TDm5gowAYl1nNRweGkmWKp2FZijt0k8ZGWl0PefOxIlmkphyV9V6tpemBs+3ESGmvv/5KcX/e+ZWhnNOT9Hw2CaEHXZQ5bUK1mPFhG8N5XXrmhaFMOHhaQ=
  on:
    tags: true
    repo: alejogiley/pypoc
    python: 3.6
